add install in cmake and auto change desktop file
TAMS-Group/scriptpanel pull request #3
Opened 2021-07-11 14:57 UTC by lianghongzhuo

2021-07-19 20:45 UTC, v4hn requested changes
Thanks for looking at it, but the patch is inconsistent with multiple issues. I added feedback.

2021-07-19 20:45 UTC, v4hn commented on script_panel.desktop-template
> +Exec=/bin/bash -c 'scriptpanel ~/scripts_folder'
:-1: 
When you execute a desktop file by clicking, it will reset the environment and the scripts you run from scriptpanel might not find your ROS workspace or the `ROS_MASTER_URI`.
I added the additional source here to solve the problem on the PR2 basestation.

2021-07-19 20:45 UTC, v4hn commented on build.sh
> +cp script_panel.desktop $HOME/Desktop
The file should go to `$HOME/.local/share/applications` instead. You also don't need the `chmod +x` above then.

2021-07-19 20:45 UTC, v4hn commented on script_panel.desktop-template
>  Type=Application
A standard naming would be `script_panel.desktop.in` instead.

2021-07-19 20:45 UTC, v4hn commented on build.sh
> +cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/bin
This install prefix only works if you actually have `$HOME/bin` in your path (privately I use `$HOME/local/bin` instead for example, other might use `.local/bin` as used by `pip install --user`).

I would prefer to leave out the install step from the script altogether because the user should/must know better.
It's better to tell the user to copy the 3 files to (1) a local folder in $PATH, (2) `$HOME/.local/share/applications/` and (3) `$HOME/.icons`.

2021-07-19 20:45 UTC, v4hn commented on build.sh
> +sed -e "s,Icon=.*,Icon=$PWD/scriptpanel.svg,g" script_panel.desktop-template > script_panel.desktop
The icon should be copied as well instead of updating the desktop file! There is no need to modify the desktop file at all!
The easiest location is `$HOME/.icons/` (I believe this is what I did on the PR2 basestation),
the "more correct" install step would install to `$HOME/.local/share/icons/hicolor/scalable` but I'm not sure that works without some further steps.

2021-07-19 22:37 UTC, lianghongzhuo commented
Thanks for your review, I have updated the code according to your comments. For the install position, we can guide the user to specify the install position by themselves.
For the icon, I found that ubuntu requires a png file to show the icon correctly.

2021-07-20 07:57 UTC, v4hn commented
Let's talk about this in person later this week.
I would like to verify how I set it up for the PR2 base station first.


Michael

2021-07-21 09:04 UTC, merged